export const APP_EVENT_DISCRIMINATOR = "kind";

export const PASS_TURN_EVENT_KIND = "PASS_TURN";
export const CHAT_MESSAGE_SENT_EVENT_KIND = "CHAT_MESSAGE_SENT";
export const CHAT_MESSAGES_READ_EVENT_KIND = "CHAT_MESSAGES_READ";

export const EVENT_KIND_LIST = [
  PASS_TURN_EVENT_KIND,
  CHAT_MESSAGE_SENT_EVENT_KIND,
  CHAT_MESSAGES_READ_EVENT_KIND,
] as const;

export const EVENT_STATUS_LIST = [
  "SENT",
  "RECEIVED",
  "PROCESSED",
  "ERRORED",
] as const;
