export const AI_AGENT_AUTO_MODE = "AUTO";
export const AI_AGENT_STANDBY_MODE = "STANDBY";
export const AI_AGENT_ASLEEP_MODE = "ASLEEP";

export const AI_AGENT_MODE_LIST = [
  AI_AGENT_AUTO_MODE,
  AI_AGENT_STANDBY_MODE,
  AI_AGENT_ASLEEP_MODE,
] as const;
